name: Workflow
on: [push]

jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install
      - name: Install Faker
        run: composer require fzaninotto/Faker
      - name: Run chromedriver
        run: nohup $CHROMEWEBDRIVER/chromedriver --url-base=/wd/hub /dev/null 2>&1 &
      - name: Run test
        run: php vendor/bin/codecept run --steps -vvv --xml
      - name: JUnit Report Action
        if: always()
        uses: mikepenz/action-junit-report@v2.4.2
        with:
          report_paths: 'tests/_output/report.xml'